spring:
  application:
    name: proyectoarq-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/proyectoarq_db
    username: postgres
    password: Oreo_2005
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
server:
  port: 8080

jwt:
  secret: 9a4f4342d0a0f44b0d0c3d4f4e5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a
  expiration: 86400000 # 1 day in milliseconds
